create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 18),
  score integer not null check (score between 0 and 1000000),
  hits integer not null check (hits between 0 and 10000),
  created_at timestamptz not null default now()
);

create index if not exists scores_score_desc_idx
  on public.scores (score desc);

alter table public.scores enable row level security;

-- Não crie políticas públicas. A API da Vercel acessa a tabela no servidor.

